# ── PHASE 1: the host ────────────────────────────────────────────────────────
# Purely additive. Nothing here touches the running container service, so the
# site stays up while the instance is built and configured alongside it.

resource "aws_lightsail_key_pair" "main" {
  name = "${var.instance_name}-key"

  # Public key is READ FROM DISK, never generated by Terraform — a generated
  # key would put the private half in state. tfvars cannot call functions, so
  # the path is the variable and the read happens here.
  public_key = file(pathexpand(var.ssh_public_key_path))
}

resource "aws_lightsail_instance" "app" {
  name              = var.instance_name
  availability_zone = var.availability_zone
  blueprint_id      = var.blueprint_id
  bundle_id         = var.bundle_id
  key_pair_name     = aws_lightsail_key_pair.main.name
  ip_address_type   = "dualstack"

  # G4 — user_data is ForceNew. Editing bootstrap.sh DESTROYS AND RECREATES
  # this instance on the next apply, taking the databases with it. The script
  # is deliberately minimal so it never needs to change; everything else is
  # Ansible's job (AD-7). Treat any plan showing replacement here as data loss.
  user_data = file("${path.module}/bootstrap.sh")

  add_on {
    type          = "AutoSnapshot"
    snapshot_time = "06:00" # UTC
    status        = "Enabled"
  }

  tags = merge(
    local.common_tags,
    {
      Name = var.instance_name
    }
  )
}

resource "aws_lightsail_static_ip" "app" {
  name = "${var.instance_name}-ip"
}

# G9 — a static IP is free while ATTACHED to a running instance and ~$3.60/mo
# while merely allocated. A partial destroy can orphan one.
resource "aws_lightsail_static_ip_attachment" "app" {
  static_ip_name = aws_lightsail_static_ip.app.name
  instance_name  = aws_lightsail_instance.app.name
}

# G3 — THIS RESOURCE IS AUTHORITATIVE. It replaces the instance's entire
# firewall rule set rather than merging into it. Every port the host needs must
# appear below; deleting the port 22 block removes SSH access on the next apply.
resource "aws_lightsail_instance_public_ports" "app" {
  instance_name = aws_lightsail_instance.app.name

  # Must stay open to the world: Let's Encrypt HTTP-01 validates the origin-*
  # names over port 80, and it cannot be restricted to CloudFront's ranges
  # because Lightsail firewalls cannot reference managed prefix lists (G11).
  # The origin is protected at the application layer instead, by Caddy's
  # X-Origin-Verify check (AD-8).
  port_info {
    protocol   = "tcp"
    from_port  = 80
    to_port    = 80
    cidrs      = ["0.0.0.0/0"]
    ipv6_cidrs = ["::/0"]
  }

  port_info {
    protocol   = "tcp"
    from_port  = 443
    to_port    = 443
    cidrs      = ["0.0.0.0/0"]
    ipv6_cidrs = ["::/0"]
  }

  # Never 0.0.0.0/0 — enforced by a validation on the variable.
  port_info {
    protocol  = "tcp"
    from_port = 22
    to_port   = 22
    cidrs     = var.ssh_allowed_cidrs
  }
}
